/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PesquisarRouteImport } from './routes/pesquisar'
import { Route as ProdutorIdRouteImport } from './routes/produtor.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PesquisarRoute = PesquisarRouteImport.update({
  id: '/pesquisar',
  path: '/pesquisar',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutorIdRoute = ProdutorIdRouteImport.update({
  id: '/produtor/$id',
  path: '/produtor/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/cadastro': typeof CadastroRoute
  '/calendario': typeof CalendarioRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/pesquisar': typeof PesquisarRoute
  '/produtor/$id': typeof ProdutorIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/cadastro': typeof CadastroRoute
  '/calendario': typeof CalendarioRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/pesquisar': typeof PesquisarRoute
  '/produtor/$id': typeof ProdutorIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/cadastro': typeof CadastroRoute
  '/calendario': typeof CalendarioRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/pesquisar': typeof PesquisarRoute
  '/produtor/$id': typeof ProdutorIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/biblioteca'
    | '/cadastro'
    | '/calendario'
    | '/feed'
    | '/login'
    | '/perfil'
    | '/pesquisar'
    | '/produtor/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/biblioteca'
    | '/cadastro'
    | '/calendario'
    | '/feed'
    | '/login'
    | '/perfil'
    | '/pesquisar'
    | '/produtor/$id'
  id:
    | '__root__'
    | '/'
    | '/biblioteca'
    | '/cadastro'
    | '/calendario'
    | '/feed'
    | '/login'
    | '/perfil'
    | '/pesquisar'
    | '/produtor/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BibliotecaRoute: typeof BibliotecaRoute
  CadastroRoute: typeof CadastroRoute
  CalendarioRoute: typeof CalendarioRoute
  FeedRoute: typeof FeedRoute
  LoginRoute: typeof LoginRoute
  PerfilRoute: typeof PerfilRoute
  PesquisarRoute: typeof PesquisarRoute
  ProdutorIdRoute: typeof ProdutorIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pesquisar': {
      id: '/pesquisar'
      path: '/pesquisar'
      fullPath: '/pesquisar'
      preLoaderRoute: typeof PesquisarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtor/$id': {
      id: '/produtor/$id'
      path: '/produtor/$id'
      fullPath: '/produtor/$id'
      preLoaderRoute: typeof ProdutorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BibliotecaRoute: BibliotecaRoute,
  CadastroRoute: CadastroRoute,
  CalendarioRoute: CalendarioRoute,
  FeedRoute: FeedRoute,
  LoginRoute: LoginRoute,
  PerfilRoute: PerfilRoute,
  PesquisarRoute: PesquisarRoute,
  ProdutorIdRoute: ProdutorIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
